version: '3.2'

services:
  database:
    image: postgres
    container_name: wecodeit-database
    restart: always

    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=root
      - POSTGRES_DB=wecodeit

    ports:
      - '5432:5432'
